version: "3.8"

services:
  go-file-server-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: go-file-server-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ROOT_DIR=/app/storage
    volumes:
      # 개발 환경에서는 로컬 디렉토리를 직접 마운트
      - ../storage:/app/storage
    networks:
      - dev-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  dev-network:
    driver: bridge
